version: "3"
services:
  image-server:
    build: ./
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "9222:9222"
    tty: true

  mongo-server:
    image: "mongo"
    ports:
      - 27017:27017
